# Generated by Django 4.2 on 2026-05-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('nlp', 'NLP'), ('cv', 'Computer Vision'), ('dl', 'Deep Learning'), ('ml', 'Machine Learning'), ('gen', 'Generative AI')], max_length=20)),
                ('tech_stack', models.CharField(help_text='Comma separated tech stack', max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_placeholder', models.CharField(default='#1a1a2e', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Programming Languages'), ('aiml', 'AI / ML'), ('frameworks', 'Frameworks & Libraries'), ('tools', 'Tools & DevOps')], max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='0-100')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
